{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wsr",
    "module": "naoko",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "naoko-1.0.5.jar",
          "url": "naoko-1.0.5.jar",
          "size": 79868,
          "sha512": "29ad2fd4cc1bd24d6eb70fa2f434774923af7c609cec86a3e6641908b69f19fdec5950ca420eb87067246bad4d2e6f226a721238cd16fb678a3314759bedc7f6",
          "sha256": "b45ad454ce2f98c7ca093ff9644709136a2e7464bd33a81500300776baf27d8e",
          "sha1": "78d06fc80857012e831bbf59104d127ac016277a",
          "md5": "308677e4f1d782ec1641431f991c88db"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.5.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "naoko-1.0.5.jar",
          "url": "naoko-1.0.5.jar",
          "size": 79868,
          "sha512": "29ad2fd4cc1bd24d6eb70fa2f434774923af7c609cec86a3e6641908b69f19fdec5950ca420eb87067246bad4d2e6f226a721238cd16fb678a3314759bedc7f6",
          "sha256": "b45ad454ce2f98c7ca093ff9644709136a2e7464bd33a81500300776baf27d8e",
          "sha1": "78d06fc80857012e831bbf59104d127ac016277a",
          "md5": "308677e4f1d782ec1641431f991c88db"
        }
      ]
    }
  ]
}
