{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wsr",
    "module": "content-type-checker",
    "version": "0.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "content-type-checker-0.0.4.jar",
          "url": "content-type-checker-0.0.4.jar",
          "size": 26356,
          "sha512": "57f8e10f04e30bb44ca40829bf87a0818ee74dbac6306e635026b635ef4d63918d940ddfac7aaf2dd1da5435d4384f6d2a6fe3ece400928ead30b9b26d09f3a1",
          "sha256": "99721d57d36b038a911707c0cede39442ab3c7ad7502cadc00cf575ec46ca5bc",
          "sha1": "ac731e5ad2bd3ca226b02825dd2c82fd7a2826ac",
          "md5": "a5780e067e17fe9fcf655507d04b0ea3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.5.30"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "content-type-checker-0.0.4.jar",
          "url": "content-type-checker-0.0.4.jar",
          "size": 26356,
          "sha512": "57f8e10f04e30bb44ca40829bf87a0818ee74dbac6306e635026b635ef4d63918d940ddfac7aaf2dd1da5435d4384f6d2a6fe3ece400928ead30b9b26d09f3a1",
          "sha256": "99721d57d36b038a911707c0cede39442ab3c7ad7502cadc00cf575ec46ca5bc",
          "sha1": "ac731e5ad2bd3ca226b02825dd2c82fd7a2826ac",
          "md5": "a5780e067e17fe9fcf655507d04b0ea3"
        }
      ]
    }
  ]
}
