{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wsr",
    "module": "content-type-checker",
    "version": "0.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "content-type-checker-0.0.4.jar",
          "url": "content-type-checker-0.0.4.jar",
          "size": 26356,
          "sha512": "3ee3f7711150fdefb744b39b1b6d662746b7582dc2e6bb25f145743dbef1dfce1d4a894367315c3d938b43892ca73a198886db10623c5e236822f4271ac0428a",
          "sha256": "69b572791e577ef95e76d37b8f2c53a1a201bb0db663a077d8027839adee6368",
          "sha1": "8bac0b0485c4af9fc2658da44c9ff06d0bfc6b52",
          "md5": "824160ba051fe950113e4308e9513898"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.5.30"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "content-type-checker-0.0.4.jar",
          "url": "content-type-checker-0.0.4.jar",
          "size": 26356,
          "sha512": "3ee3f7711150fdefb744b39b1b6d662746b7582dc2e6bb25f145743dbef1dfce1d4a894367315c3d938b43892ca73a198886db10623c5e236822f4271ac0428a",
          "sha256": "69b572791e577ef95e76d37b8f2c53a1a201bb0db663a077d8027839adee6368",
          "sha1": "8bac0b0485c4af9fc2658da44c9ff06d0bfc6b52",
          "md5": "824160ba051fe950113e4308e9513898"
        }
      ]
    }
  ]
}
