{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wsr",
    "module": "naoko",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "naoko-1.0.jar",
          "url": "naoko-1.0.jar",
          "size": 77353,
          "sha512": "13491dfe5a619f1b743c33089198386af42df1617b9c6a3dcbe947bf0aa61fd67ac4884e57a7cd1a530b185130b25ba75db6980998460ffcc436be674ec87937",
          "sha256": "572cdbfa0f34f0fb6ec1f88176d5c12e6be62d6003c7f9bb2c993a6ec8b9453a",
          "sha1": "4311c5d085ad03cde9f5935e4df4af3cc5544dd8",
          "md5": "f906878d570e9dfee165b36f2f00dd8a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.5.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "naoko-1.0.jar",
          "url": "naoko-1.0.jar",
          "size": 77353,
          "sha512": "13491dfe5a619f1b743c33089198386af42df1617b9c6a3dcbe947bf0aa61fd67ac4884e57a7cd1a530b185130b25ba75db6980998460ffcc436be674ec87937",
          "sha256": "572cdbfa0f34f0fb6ec1f88176d5c12e6be62d6003c7f9bb2c993a6ec8b9453a",
          "sha1": "4311c5d085ad03cde9f5935e4df4af3cc5544dd8",
          "md5": "f906878d570e9dfee165b36f2f00dd8a"
        }
      ]
    }
  ]
}
