{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wsr",
    "module": "naoko",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "naoko-1.0.jar",
          "url": "naoko-1.0.jar",
          "size": 76867,
          "sha512": "53cb8526f7ec435c6f91d4bc61630adb5a2ab4c3ae3343a68d8d397a4fd37a84e9d0fe586e2f37099db643bd7827c1dd33a4ecc24007a857e7716ebefbe1d4b3",
          "sha256": "91e83702ea1f6f627f7a564e8ea3dd8ad8ea7abbb87c8749c30eb7a0f066e2cc",
          "sha1": "94f6ad07a692ea9197da95de911f7debb59c959e",
          "md5": "4dd7e3da5c0912cf9b82702c08eacdb4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.5.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "naoko-1.0.jar",
          "url": "naoko-1.0.jar",
          "size": 76867,
          "sha512": "53cb8526f7ec435c6f91d4bc61630adb5a2ab4c3ae3343a68d8d397a4fd37a84e9d0fe586e2f37099db643bd7827c1dd33a4ecc24007a857e7716ebefbe1d4b3",
          "sha256": "91e83702ea1f6f627f7a564e8ea3dd8ad8ea7abbb87c8749c30eb7a0f066e2cc",
          "sha1": "94f6ad07a692ea9197da95de911f7debb59c959e",
          "md5": "4dd7e3da5c0912cf9b82702c08eacdb4"
        }
      ]
    }
  ]
}
